name: CI & CD

on:
  push:
    branches:
      - master
      - github-action
  pull_request:
    branches:
      - master
      - github-action
        
jobs:
  ci:
    name: Source update and Testing
    runs-on: ubuntu-latest
    container:
      image: node

    steps:
      - uses: actions/checkout@v2
      - name: Set env files
        run: |
          cp .env.sample .env
          cp config/.env.test.sample config/.env.test
      - name: Install & Tests
        run: |
          npm install
          npm test
      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v1
        with:
          name: codecov-jaebook-server
          fail_ci_if_error: true
  cd:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: ci

    steps:
    - name: SSH and Build Docker image and Push
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.SERVER_FILE_DIRECTORY }}
          git stash
          git pull origin master
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.SERVER_IMAGE_NAME }} .
          docker tag ${{ secrets.SERVER_IMAGE_NAME }} ${{ secrets.DOCKER_USER }}/${{ secrets.SERVER_IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ secrets.SERVER_IMAGE_NAME }} ${{ secrets.DOCKER_USER }}/${{ secrets.SERVER_IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.SERVER_IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/${{ secrets.SERVER_IMAGE_NAME }}:latest
          docker image prune -f